#!/usr/bin/env python3
"""Bundles index.html + css/style.css + js/*.js + characters/*.js + every asset
image actually referenced by the game into one self-contained standalone.html.

Images are embedded as base64 data URIs. Rather than textually rewriting every
place the code builds an image path (literal strings, string concatenation like
SH_IMG + d.img, etc.), we patch HTMLImageElement.prototype.src once at the top
of the bundle so any assignment of a known relative path is transparently
redirected to its data URI. Game code itself is untouched.

Re-run this after editing the modular source (css/js/characters/index.html);
it regenerates standalone.html from scratch.
"""
import base64
import pathlib
import re
import json

ROOT = pathlib.Path(__file__).resolve().parent

SCRIPT_ORDER = [
    "characters/registry.js",
    "characters/itadori.js",
    "characters/megumi.js",
    "characters/gojo.js",
    "characters/sukuna_heian_atlas.js",
    "characters/sukuna_heian.js",
    "js/meta.js",
    "js/story.js",
    "js/shibuya.js",
    "js/companion.js",
    "js/heian.js",
    "js/prestige.js",
    "js/enemies.js",
    "js/dialogue.js",
    "js/game.js",
]

MIME = {
    ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
    ".webp": "image/webp", ".gif": "image/gif", ".svg": "image/svg+xml",
}


def find_referenced_assets():
    paths = set()
    text_blobs = [(ROOT / "index.html").read_text()]
    text_blobs.append((ROOT / "css" / "style.css").read_text())
    for rel in SCRIPT_ORDER:
        text_blobs.append((ROOT / rel).read_text())
    blob = "\n".join(text_blobs)
    for m in re.finditer(r"assets/[A-Za-z0-9_./-]+\.(?:png|jpg|jpeg|webp|gif|svg)", blob):
        paths.add(m.group(0))
    # Concatenated paths (e.g. SH_IMG + d.img) aren't literal strings, so add
    # shibuya map images explicitly by resolving SH_IMG against each `img:` filename.
    shibuya_js = (ROOT / "js" / "shibuya.js").read_text()
    base_match = re.search(r"SH_IMG\s*=\s*'([^']+)'", shibuya_js)
    if base_match:
        base = base_match.group(1)
        for fn in re.findall(r"img:\s*'([^']+\.(?:png|jpg|jpeg|webp|gif|svg))'", shibuya_js):
            paths.add(base + fn)
    return sorted(paths)


def build_asset_map(asset_paths):
    asset_map = {}
    for rel in asset_paths:
        fp = ROOT / rel
        if not fp.is_file():
            print(f"WARNING: referenced asset missing on disk, skipping: {rel}")
            continue
        mime = MIME.get(fp.suffix.lower(), "application/octet-stream")
        data = base64.b64encode(fp.read_bytes()).decode("ascii")
        asset_map[rel] = f"data:{mime};base64,{data}"
    return asset_map


def main():
    asset_paths = find_referenced_assets()
    asset_map = build_asset_map(asset_paths)
    total_bytes = sum(len(v) for v in asset_map.values())
    print(f"Embedding {len(asset_map)} assets (~{total_bytes / 1_000_000:.1f} MB as base64)")

    html = (ROOT / "index.html").read_text()

    css = (ROOT / "css" / "style.css").read_text()
    html = html.replace(
        '<link rel="stylesheet" href="css/style.css" />',
        f"<style>\n{css}\n</style>",
    )

    interceptor = (
        "<script>\n"
        "// Auto-generated by build_standalone.py — redirects known relative asset\n"
        "// paths to their embedded data URIs so the rest of the game code (which\n"
        "// still says things like img.src = 'assets/fx/blue_orb.png') needs no changes.\n"
        f"const __ASSET_DATA__ = {json.dumps(asset_map)};\n"
        "(function () {\n"
        "  const desc = Object.getOwnPropertyDescriptor(HTMLImageElement.prototype, 'src');\n"
        "  Object.defineProperty(HTMLImageElement.prototype, 'src', {\n"
        "    configurable: true,\n"
        "    get() { return desc.get.call(this); },\n"
        "    set(v) { desc.set.call(this, __ASSET_DATA__[v] || v); },\n"
        "  });\n"
        "})();\n"
        "</script>\n"
    )

    script_blocks = [interceptor]
    for rel in SCRIPT_ORDER:
        code = (ROOT / rel).read_text()
        script_blocks.append(f"<script>\n{code}\n</script>\n")
        html = html.replace(f'<script src="{rel}"></script>\n', "")
        html = html.replace(f'<script src="{rel}"></script>', "")

    html = html.replace("</body>", "\n".join(script_blocks) + "</body>")

    out = ROOT / "standalone.html"
    out.write_text(html)
    print(f"Wrote {out} ({out.stat().st_size / 1_000_000:.1f} MB)")


if __name__ == "__main__":
    main()
